import * as getters from './common_getters'
import * as actions from './common_actions'
import * as mutations from './common_mutations'

export const state = {
  naming_convention: null,
  naming_conventions: [{ value: "new", label: "Create" }],
  custom_datasets: [
    {
      id: "1", name: "3D Model", pattern: "e(?P<X>[0-9]{3})n(?P<Y>[0-9]{4})_(.+)_(dem|dsm|chm|fcm|dtm)([0-9]+)c?m_v([0-9]+)cm_mga(?P<zone>[0-9]{2})+", description: "3D model of the structures collected",
      formats: [
        { label: "Shape files", value: "shp" },
        { label: "File Geodatabase", value: "fgdb" },
        { label: "MapInfo TAB", value: "tab" },
        { label: "AutoCAD DXF", value: "dxf" }
      ]
    },
    {
      id: "2", name: "CHM", pattern: "e(?P<X>[0-9]{3})n(?P<Y>[0-9]{4})_(.+)_(dem|dsm|chm|fcm|dtm)([0-9]+)c?m_v([0-9]+)cm_mga(?P<zone>[0-9]{2})+",
      description: "Canopy height model - Raster dataset that maps the tree height as a continuous surface. Each pixel in the CHM represents the tree overstory height above the underlying ground topography.",
      formats: [
        { label: "GeoTiff (.tif/.tiff)", value: "tiff" },
        { label: "ASCII (.asc)", value: "asc" }
      ]
    }
  ],
  standard_datasets: [],
  current_standard_dataset: {
    id: null,
    created_by: null,
    name: null,
    is_public: true,
    description: null,
    classified_pointcloud: {
      pattern: ["e", "Easting KM", "n", "Northing KM", "Any Word", "Year", "Month Name", "Date", "_mpts-", "Classification Level", "_v", "Linear Unit", "_", "Datum", "-mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['las', 'laz']
    },
    unclassified_pointcloud: {
      pattern: ["e", "Easting KM", "n", "Northing KM", "Any Word", "Year", "Month Name", "Date", "_", "raw|unc", "-", "Swath", "_v", "Linear Unit", "_", "Datum", "-mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['las', 'laz']
    },
    mkp_pointcloud: {
      pattern: ["e", "Easting KM", "n", "Northing KM", "Any Word", "Year", "Month Name", "Date", "_mkp_v", "Linear Unit", "_", "Datum", "-mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['las', 'laz']
    },
    dem: {
      pattern: ["e", "Easting KM", "n", "Northing KM", "Any Word", "Year", "Month Name", "Date", "_dem", "Linear Unit", "_", "mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['tiff']
    },
    dsm: {
      pattern: ["e", "Easting KM", "n", "Northing KM", "Any Word", "Year", "Month Name", "Date", "_dsm", "Linear Unit", "_", "mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['tiff']
    },
    imagery: {
      pattern: ["e", "Easting KM", "n", "Northing KM", "Any Word", "Year", "Month Name", "Date", "_", "Image Type", "_", "Linear Unit", "_", "mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['tiff']
    },
    contours: {
      pattern: ["Any Word", "_contour_", "Linear Unit", "_", "mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['shp']
    },
    trajectory: {
      pattern: ["Any Word", "_trajectory_", "mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['shp']
    },
    tileindex: {
      pattern: ["Any Word", "_tileindex_", "Linear Unit", "_", "mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['shp']
    },
    video: {
      pattern: ["Any Word", "_video_"],
      pattern_regex: null,
      formats: ['mp4']
    },
    controlpoints: {
      pattern: ["Any Word", "_gcp_", "mga", "UTM Zone"],
      pattern_regex: null,
      formats: ['shp']
    },
    report: {
      pattern: ["Any Word", "_report_"],
      pattern_regex: null,
      formats: ['pdf']
    },
    metadata: {
      pattern: ["Any Word", "_meta_"],
      pattern_regex: null,
      formats: ['xml']
    }
  },
  video_resolution: [
    { label: "360p", value: 360 },
    { label: "480p", value: 480 },
    { label: "720p", value: 720 },
    { label: "1080p", value: 1080 },
  ],
  scan_angle: [
    { label: "≤20° Total FOV", value: 20 },
    { label: "≤25° Total FOV", value: 25 },
    { label: "≤30° Total FOV", value: 30 },
    { label: "≤35° Total FOV", value: 35 },
    { label: "≤40° Total FOV", value: 40 },
    { label: "≤45° Total FOV", value: 45 },
    { label: "≤50° Total FOV", value: 50 },
    { label: "≤55° Total FOV", value: 55 },
    { label: "≤60° Total FOV", value: 60 },
  ],
  pc_versions: [
    { label: "LAS 1.2", value: 1.2 },
    { label: "LAS 1.3", value: 1.3 },
    { label: "LAS 1.4", value: 1.4 }
  ],
  pdrf_formats: [
    { label: "PDRF 0", value: 0 },
    { label: "PDRF 1", value: 1 },
    { label: "PDRF 2", value: 2 },
    { label: "PDRF 3", value: 3 },
    { label: "PDRF 4", value: 4 },
    { label: "PDRF 5", value: 5 },
    { label: "PDRF 6", value: 6 },
    { label: "PDRF 7", value: 7 },
    { label: "PDRF 8", value: 8 },
    { label: "PDRF 9", value: 9 },
    { label: "PDRF 10",value: 10 }
  ],
  classification_old: [
    { class: 0, name: "Created, never classified", required: null, level: null },
    { class: 1, name: "Unclassified", required: null, level: null },
    { class: 2, name: "Ground", required: null, level: null },
    { class: 3, name: "Low Vegetation", required: null, level: null },
    { class: 4, name: "Medium Vegetation", required: null, level: null },
    { class: 5, name: "High Vegetation", required: null, level: null },
    { class: 6, name: "Building", required: null, level: null },
    { class: 7, name: "Low Point (noise)", required: null, level: null },
    { class: 8, name: "Model Key-point", required: null, level: null },
    { class: 9, name: "Water", required: null, level: null },
    { class: 10, name: "Reserved", required: null, level: null },
    { class: 11, name: "Reserved", required: null, level: null },
    { class: 12, name: "Overlap Points", required: null, level: null }
  ],
  classification_new: [
    { class: 0, name: "Created, never classified", required: null, level: null },
    { class: 1, name: "Unclassified", required: null, level: null },
    { class: 2, name: "Ground", required: null, level: null },
    { class: 3, name: "Low Vegetation", required: null, level: null },
    { class: 4, name: "Medium Vegetation", required: null, level: null },
    { class: 5, name: "High Vegetation", required: null, level: null },
    { class: 6, name: "Building", required: null, level: null },
    { class: 7, name: "Low Point (noise)", required: null, level: null },
    { class: 8, name: "Model Key-point", required: null, level: null },
    { class: 9, name: "Water", required: null, level: null },
    { class: 10, name: "Rail", required: null, level: null },
    { class: 11, name: "Road Surface", required: null, level: null },
    { class: 12, name: "Overlap Points", required: null, level: null },
    { class: 13, name: "Wire – Guard", required: null, level: null },
    { class: 14, name: "Wire – Conductor", required: null, level: null },
    { class: 15, name: "Transmission Tower", required: null, level: null },
    { class: 16, name: "Wire-structure Connector", required: null, level: null },
    { class: 17, name: "Bridge Deck", required: null, level: null },
    { class: 18, name: "High Noise", required: null, level: null }
  ],
  hcs: [
    { 'value': 28349, 'label': 'GDA94 MGA Z49', 'sublabel': 'australia; EPSG: 28349' },
    { 'value': 28350, 'label': 'GDA94 MGA Z50', 'sublabel': 'australia; EPSG: 28350' },
    { 'value': 28351, 'label': 'GDA94 MGA Z51', 'sublabel': 'australia; EPSG: 28351' },
    { 'value': 28352, 'label': 'GDA94 MGA Z52', 'sublabel': 'australia; EPSG: 28352' },
    { 'value': 28353, 'label': 'GDA94 MGA Z53', 'sublabel': 'australia; EPSG: 28353' },
    { 'value': 28354, 'label': 'GDA94 MGA Z54', 'sublabel': 'australia; EPSG: 28354' },
    { 'value': 28355, 'label': 'GDA94 MGA Z55', 'sublabel': 'australia; EPSG: 28355' },
    { 'value': 28356, 'label': 'GDA94 MGA Z56', 'sublabel': 'australia; EPSG: 28356' },
    { 'value': 7849, 'label': 'GDA2020 MGA Z49', 'sublabel': 'australia; EPSG: 7849' },
    { 'value': 7850, 'label': 'GDA2020 MGA Z50', 'sublabel': 'australia; EPSG: 7850' },
    { 'value': 7851, 'label': 'GDA2020 MGA Z51', 'sublabel': 'australia; EPSG: 7851' },
    { 'value': 7852, 'label': 'GDA2020 MGA Z52', 'sublabel': 'australia; EPSG: 7852' },
    { 'value': 7853, 'label': 'GDA2020 MGA Z53', 'sublabel': 'australia; EPSG: 7853' },
    { 'value': 7854, 'label': 'GDA2020 MGA Z54', 'sublabel': 'australia; EPSG: 7854' },
    { 'value': 7855, 'label': 'GDA2020 MGA Z55', 'sublabel': 'australia; EPSG: 7855' },
    { 'value': 7856, 'label': 'GDA2020 MGA Z56', 'sublabel': 'australia; EPSG: 7856' },
    { 'value': 4938, 'label': 'GDA94', 'sublabel': 'australia; EPSG: 4938' },
    { 'value': 7844, 'label': 'GDA2020', 'sublabel': 'australia; EPSG: 7844' },
    { 'value': 3111, 'label': 'VicGrid94', 'sublabel': 'australia; EPSG: 3111' },
    { 'value': 2193, 'label': 'NZTM2000', 'sublabel': 'new-zealand; EPSG: 2193' },
    { 'value': 4167, 'label': 'NZGD2000', 'sublabel': 'new-zealand; EPSG: 4167' },
    { 'value': 4326, 'label': 'WGS84', 'sublabel': 'world; EPSG: 4326' },
    { 'value': 32701, 'label': 'UTMZ1S', 'sublabel': 'world; EPSG: 32701' },
    { 'value': 32702, 'label': 'UTMZ2S', 'sublabel': 'world; EPSG: 32702' },
    { 'value': 32703, 'label': 'UTMZ3S', 'sublabel': 'world; EPSG: 32703' },
    { 'value': 32704, 'label': 'UTMZ4S', 'sublabel': 'world; EPSG: 32704' },
    { 'value': 32705, 'label': 'UTMZ5S', 'sublabel': 'world; EPSG: 32705' },
    { 'value': 32706, 'label': 'UTMZ6S', 'sublabel': 'world; EPSG: 32706' },
    { 'value': 32707, 'label': 'UTMZ7S', 'sublabel': 'world; EPSG: 32707' },
    { 'value': 32708, 'label': 'UTMZ8S', 'sublabel': 'world; EPSG: 32708' },
    { 'value': 32709, 'label': 'UTMZ9S', 'sublabel': 'world; EPSG: 32709' },
    { 'value': 32710, 'label': 'UTMZ10S', 'sublabel': 'world; EPSG: 32710' },
    { 'value': 32711, 'label': 'UTMZ11S', 'sublabel': 'world; EPSG: 32711' },
    { 'value': 32712, 'label': 'UTMZ12S', 'sublabel': 'world; EPSG: 32712' },
    { 'value': 32713, 'label': 'UTMZ13S', 'sublabel': 'world; EPSG: 32713' },
    { 'value': 32714, 'label': 'UTMZ14S', 'sublabel': 'world; EPSG: 32714' },
    { 'value': 32715, 'label': 'UTMZ15S', 'sublabel': 'world; EPSG: 32715' },
    { 'value': 32716, 'label': 'UTMZ16S', 'sublabel': 'world; EPSG: 32716' },
    { 'value': 32717, 'label': 'UTMZ17S', 'sublabel': 'world; EPSG: 32717' },
    { 'value': 32718, 'label': 'UTMZ18S', 'sublabel': 'world; EPSG: 32718' },
    { 'value': 32719, 'label': 'UTMZ19S', 'sublabel': 'world; EPSG: 32719' },
    { 'value': 32720, 'label': 'UTMZ20S', 'sublabel': 'world; EPSG: 32720' },
    { 'value': 32721, 'label': 'UTMZ21S', 'sublabel': 'world; EPSG: 32721' },
    { 'value': 32722, 'label': 'UTMZ22S', 'sublabel': 'world; EPSG: 32722' },
    { 'value': 32723, 'label': 'UTMZ23S', 'sublabel': 'world; EPSG: 32723' },
    { 'value': 32724, 'label': 'UTMZ24S', 'sublabel': 'world; EPSG: 32724' },
    { 'value': 32725, 'label': 'UTMZ25S', 'sublabel': 'world; EPSG: 32725' },
    { 'value': 32726, 'label': 'UTMZ26S', 'sublabel': 'world; EPSG: 32726' },
    { 'value': 32727, 'label': 'UTMZ27S', 'sublabel': 'world; EPSG: 32727' },
    { 'value': 32728, 'label': 'UTMZ28S', 'sublabel': 'world; EPSG: 32728' },
    { 'value': 32729, 'label': 'UTMZ29S', 'sublabel': 'world; EPSG: 32729' },
    { 'value': 32730, 'label': 'UTMZ30S', 'sublabel': 'world; EPSG: 32730' },
    { 'value': 32731, 'label': 'UTMZ31S', 'sublabel': 'world; EPSG: 32731' },
    { 'value': 32732, 'label': 'UTMZ32S', 'sublabel': 'world; EPSG: 32732' },
    { 'value': 32733, 'label': 'UTMZ33S', 'sublabel': 'world; EPSG: 32733' },
    { 'value': 32734, 'label': 'UTMZ34S', 'sublabel': 'world; EPSG: 32734' },
    { 'value': 32735, 'label': 'UTMZ35S', 'sublabel': 'world; EPSG: 32735' },
    { 'value': 32736, 'label': 'UTMZ36S', 'sublabel': 'world; EPSG: 32736' },
    { 'value': 32737, 'label': 'UTMZ37S', 'sublabel': 'world; EPSG: 32737' },
    { 'value': 32738, 'label': 'UTMZ38S', 'sublabel': 'world; EPSG: 32738' },
    { 'value': 32739, 'label': 'UTMZ39S', 'sublabel': 'world; EPSG: 32739' },
    { 'value': 32740, 'label': 'UTMZ40S', 'sublabel': 'world; EPSG: 32740' },
    { 'value': 32741, 'label': 'UTMZ41S', 'sublabel': 'world; EPSG: 32741' },
    { 'value': 32742, 'label': 'UTMZ42S', 'sublabel': 'world; EPSG: 32742' },
    { 'value': 32743, 'label': 'UTMZ43S', 'sublabel': 'world; EPSG: 32743' },
    { 'value': 32744, 'label': 'UTMZ44S', 'sublabel': 'world; EPSG: 32744' },
    { 'value': 32745, 'label': 'UTMZ45S', 'sublabel': 'world; EPSG: 32745' },
    { 'value': 32746, 'label': 'UTMZ46S', 'sublabel': 'world; EPSG: 32746' },
    { 'value': 32747, 'label': 'UTMZ47S', 'sublabel': 'world; EPSG: 32747' },
    { 'value': 32748, 'label': 'UTMZ48S', 'sublabel': 'world; EPSG: 32748' },
    { 'value': 32749, 'label': 'UTMZ49S', 'sublabel': 'world; EPSG: 32749' },
    { 'value': 32750, 'label': 'UTMZ50S', 'sublabel': 'world; EPSG: 32750' },
    { 'value': 32751, 'label': 'UTMZ51S', 'sublabel': 'world; EPSG: 32751' },
    { 'value': 32752, 'label': 'UTMZ52S', 'sublabel': 'world; EPSG: 32752' },
    { 'value': 32753, 'label': 'UTMZ53S', 'sublabel': 'world; EPSG: 32753' },
    { 'value': 32754, 'label': 'UTMZ54S', 'sublabel': 'world; EPSG: 32754' },
    { 'value': 32755, 'label': 'UTMZ55S', 'sublabel': 'world; EPSG: 32755' },
    { 'value': 32756, 'label': 'UTMZ56S', 'sublabel': 'world; EPSG: 32756' },
    { 'value': 32757, 'label': 'UTMZ57S', 'sublabel': 'world; EPSG: 32757' },
    { 'value': 32758, 'label': 'UTMZ58S', 'sublabel': 'world; EPSG: 32758' },
    { 'value': 32759, 'label': 'UTMZ59S', 'sublabel': 'world; EPSG: 32759' },
    { 'value': 32760, 'label': 'UTMZ60S', 'sublabel': 'world; EPSG: 32760' },
    { 'value': 32601, 'label': 'UTMZ1N', 'sublabel': 'world; EPSG: 32601' },
    { 'value': 32602, 'label': 'UTMZ2N', 'sublabel': 'world; EPSG: 32602' },
    { 'value': 32603, 'label': 'UTMZ3N', 'sublabel': 'world; EPSG: 32603' },
    { 'value': 32604, 'label': 'UTMZ4N', 'sublabel': 'world; EPSG: 32604' },
    { 'value': 32605, 'label': 'UTMZ5N', 'sublabel': 'world; EPSG: 32605' },
    { 'value': 32606, 'label': 'UTMZ6N', 'sublabel': 'world; EPSG: 32606' },
    { 'value': 32607, 'label': 'UTMZ7N', 'sublabel': 'world; EPSG: 32607' },
    { 'value': 32608, 'label': 'UTMZ8N', 'sublabel': 'world; EPSG: 32608' },
    { 'value': 32609, 'label': 'UTMZ9N', 'sublabel': 'world; EPSG: 32609' },
    { 'value': 32610, 'label': 'UTMZ10N', 'sublabel': 'world; EPSG: 32610' },
    { 'value': 32611, 'label': 'UTMZ11N', 'sublabel': 'world; EPSG: 32611' },
    { 'value': 32612, 'label': 'UTMZ12N', 'sublabel': 'world; EPSG: 32612' },
    { 'value': 32613, 'label': 'UTMZ13N', 'sublabel': 'world; EPSG: 32613' },
    { 'value': 32614, 'label': 'UTMZ14N', 'sublabel': 'world; EPSG: 32614' },
    { 'value': 32615, 'label': 'UTMZ15N', 'sublabel': 'world; EPSG: 32615' },
    { 'value': 32616, 'label': 'UTMZ16N', 'sublabel': 'world; EPSG: 32616' },
    { 'value': 32617, 'label': 'UTMZ17N', 'sublabel': 'world; EPSG: 32617' },
    { 'value': 32618, 'label': 'UTMZ18N', 'sublabel': 'world; EPSG: 32618' },
    { 'value': 32619, 'label': 'UTMZ19N', 'sublabel': 'world; EPSG: 32619' },
    { 'value': 32620, 'label': 'UTMZ20N', 'sublabel': 'world; EPSG: 32620' },
    { 'value': 32621, 'label': 'UTMZ21N', 'sublabel': 'world; EPSG: 32621' },
    { 'value': 32622, 'label': 'UTMZ22N', 'sublabel': 'world; EPSG: 32622' },
    { 'value': 32623, 'label': 'UTMZ23N', 'sublabel': 'world; EPSG: 32623' },
    { 'value': 32624, 'label': 'UTMZ24N', 'sublabel': 'world; EPSG: 32624' },
    { 'value': 32625, 'label': 'UTMZ25N', 'sublabel': 'world; EPSG: 32625' },
    { 'value': 32626, 'label': 'UTMZ26N', 'sublabel': 'world; EPSG: 32626' },
    { 'value': 32627, 'label': 'UTMZ27N', 'sublabel': 'world; EPSG: 32627' },
    { 'value': 32628, 'label': 'UTMZ28N', 'sublabel': 'world; EPSG: 32628' },
    { 'value': 32629, 'label': 'UTMZ29N', 'sublabel': 'world; EPSG: 32629' },
    { 'value': 32630, 'label': 'UTMZ30N', 'sublabel': 'world; EPSG: 32630' },
    { 'value': 32631, 'label': 'UTMZ31N', 'sublabel': 'world; EPSG: 32631' },
    { 'value': 32632, 'label': 'UTMZ32N', 'sublabel': 'world; EPSG: 32632' },
    { 'value': 32633, 'label': 'UTMZ33N', 'sublabel': 'world; EPSG: 32633' },
    { 'value': 32634, 'label': 'UTMZ34N', 'sublabel': 'world; EPSG: 32634' },
    { 'value': 32635, 'label': 'UTMZ35N', 'sublabel': 'world; EPSG: 32635' },
    { 'value': 32636, 'label': 'UTMZ36N', 'sublabel': 'world; EPSG: 32636' },
    { 'value': 32637, 'label': 'UTMZ37N', 'sublabel': 'world; EPSG: 32637' },
    { 'value': 32638, 'label': 'UTMZ38N', 'sublabel': 'world; EPSG: 32638' },
    { 'value': 32639, 'label': 'UTMZ39N', 'sublabel': 'world; EPSG: 32639' },
    { 'value': 32640, 'label': 'UTMZ40N', 'sublabel': 'world; EPSG: 32640' },
    { 'value': 32641, 'label': 'UTMZ41N', 'sublabel': 'world; EPSG: 32641' },
    { 'value': 32642, 'label': 'UTMZ42N', 'sublabel': 'world; EPSG: 32642' },
    { 'value': 32643, 'label': 'UTMZ43N', 'sublabel': 'world; EPSG: 32643' },
    { 'value': 32644, 'label': 'UTMZ44N', 'sublabel': 'world; EPSG: 32644' },
    { 'value': 32645, 'label': 'UTMZ45N', 'sublabel': 'world; EPSG: 32645' },
    { 'value': 32646, 'label': 'UTMZ46N', 'sublabel': 'world; EPSG: 32646' },
    { 'value': 32647, 'label': 'UTMZ47N', 'sublabel': 'world; EPSG: 32647' },
    { 'value': 32648, 'label': 'UTMZ48N', 'sublabel': 'world; EPSG: 32648' },
    { 'value': 32649, 'label': 'UTMZ49N', 'sublabel': 'world; EPSG: 32649' },
    { 'value': 32650, 'label': 'UTMZ50N', 'sublabel': 'world; EPSG: 32650' },
    { 'value': 32651, 'label': 'UTMZ51N', 'sublabel': 'world; EPSG: 32651' },
    { 'value': 32652, 'label': 'UTMZ52N', 'sublabel': 'world; EPSG: 32652' },
    { 'value': 32653, 'label': 'UTMZ53N', 'sublabel': 'world; EPSG: 32653' },
    { 'value': 32654, 'label': 'UTMZ54N', 'sublabel': 'world; EPSG: 32654' },
    { 'value': 32655, 'label': 'UTMZ55N', 'sublabel': 'world; EPSG: 32655' },
    { 'value': 32656, 'label': 'UTMZ56N', 'sublabel': 'world; EPSG: 32656' },
    { 'value': 32657, 'label': 'UTMZ57N', 'sublabel': 'world; EPSG: 32657' },
    { 'value': 32658, 'label': 'UTMZ58N', 'sublabel': 'world; EPSG: 32658' },
    { 'value': 32659, 'label': 'UTMZ59N', 'sublabel': 'world; EPSG: 32659' },
    { 'value': 32660, 'label': 'UTMZ60N', 'sublabel': 'world; EPSG: 32660' }
  ],
  vcs: [
    { 'value': 5711, 'label': 'Australian Height Datum (AHD)', 'sublabel': 'australia; EPSG: 5711' },
    { 'value': 115715, 'label': 'GRS80 Ellipsoid (GDA94)', 'sublabel': 'australia; EPSG: 115715' },
    { 'value': 115765, 'label': 'GRS80 Ellipsoid (NZGD2000)', 'sublabel': 'new-zealand; EPSG: 115765' },
    { 'value': 115700, 'label': 'WGS84 Ellipsoid', 'sublabel': 'world; EPSG: 115700' },
    { 'value': 5714, 'label': 'Mean Sea Level (MSL)', 'sublabel': 'world; EPSG: 5714' },
    { 'value': 5861, 'label': 'Lowest Astronomical Tide (LAT)', 'sublabel': 'world; EPSG: 5861' },
    { 'value': 5872, 'label': 'Highest Astronomical Tide (HAT)', 'sublabel': 'world; EPSG: 5872' },
    { 'value': 5867, 'label': 'Mean Low Water (MLW)', 'sublabel': 'world; EPSG: 5867' },
    { 'value': 5868, 'label': 'Mean High Water (MHW)', 'sublabel': 'world; EPSG: 5868' },
    { 'value': 4440, 'label': 'New Zealand Vertical Datum (NZVD2009)', 'sublabel': 'new-zealand; EPSG: 4440' },
    { 'value': 5767, 'label': 'One Tree Point 1964 (OTP)', 'sublabel': 'new-zealand; EPSG: 5767' },
    { 'value': 5759, 'label': 'Auckland 1946 (AKL)', 'sublabel': 'new-zealand; EPSG: 5759' },
    { 'value': 5764, 'label': 'Moturiki 1953 (MOT)', 'sublabel': 'new-zealand; EPSG: 5764' },
    { 'value': 5762, 'label': 'Gisborne 1926 (GIS)', 'sublabel': 'new-zealand; EPSG: 5762' },
    { 'value': 5765, 'label': 'Napier 1962 (NAP)', 'sublabel': 'new-zealand; EPSG: 5765' },
    { 'value': 5769, 'label': 'Taranaki 1970 (TAR)', 'sublabel': 'new-zealand; EPSG: 5769' },
    { 'value': 5770, 'label': 'Wellington 1953 (WEL)', 'sublabel': 'new-zealand; EPSG: 5770' },
    { 'value': 5766, 'label': 'Nelson 1955 (NEL)', 'sublabel': 'new-zealand; EPSG: 5766' },
    { 'value': 5763, 'label': 'Lyttelton 1937 (LYT)', 'sublabel': 'new-zealand; EPSG: 5763' },
    { 'value': 5761, 'label': 'Dunedin 1958 (DUN)', 'sublabel': 'new-zealand; EPSG: 5761' },
    { 'value': 4458, 'label': 'Dunedin-Bluff 1960 (DBL)', 'sublabel': 'new-zealand; EPSG: 4458' },
    { 'value': 5760, 'label': 'Bluff 1955 (BLU)', 'sublabel': 'new-zealand; EPSG: 5760' },
    { 'value': 5772, 'label': 'Stewart Island 1977 (STI)' },
  ],
  all_formats: [
    { label: "ECW (.ecw)", value: "ecw" },
    { label: "GeoTiff (.tif/.tiff)", value: "tiff" },
    { label: "Jpeg (.jpg/.jp2)", value: "jpg" },
    { label: "ASCII (.asc)", value: "asc" },
    { label: "Uncompressed (.las)", value: "las" },
    { label: "Compressed (.laz)", value: "laz" },
    { label: "Shape files", value: "shp" },
    { label: "KML/KMZ", value: "kml" },
    { label: "File Geodatabase", value: "fgdb" },
    { label: "MapInfo TAB", value: "tab" },
    { label: "AutoCAD DXF", value: "dxf" },
    { label: "XML", value: "xml" },
    { label: "Adobe PDF", value: "pdf" },
    { label: "Microsoft Word", value: "doc" },
    { label: "Microsoft Excel", value: "xls" },
    { label: "MPEG-4", value: "mp4" },
    { label: "Quicktime", value: "mov" },
    { label: "Audio Video Interleave", value: "avi" },
    { label: "Material eXchange Format", value: "mxf" },
    { label: "Other", value: "other" },
  ]
}

export default {
  namespaced: true,
  state,
  getters,
  actions,
  mutations
}
