version: "3.4"
services:

  www:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./server.conf
    depends_on:
      - 'api'
      - 'mapserver'

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server.conf
    environment:
      POSTGRES_HOSTNAME: "db-postgres"
    depends_on:
      - 'db-postgres'

  db-postgres:
    image: postgis/postgis:16-3.4
    env_file: ./server.conf
    environment:
      POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"
    volumes:
      - ./backup:/backup

  mapserver:
    build:
      context: ./map
      dockerfile: Dockerfile
    env_file: ./server.conf
    environment:
      POSTGRES_HOSTNAME: "db-postgres"
    depends_on:
      - 'db-postgres'
