develop_only: &develop_only
  filters:
    branches:
      only: develop

master_only: &master_only
  filters:
    branches:
      only: master


version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps@sha256:f15719b269c2c7337d2fb29a31abf4edcfe30311291765b831e699b0ad9ae77d

jobs:
  build:
    parameters:
      image-name:
        type: string
      image-tag-suffix:
        type: string
        default: ''
      image-file:
        type: string
      docker-file-path:
        type: string
      auth-host:
        type: string
        default: ''
      auth-client-id:
        type: string
        default: ''
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build << parameters.image-name >> Docker image
          command: docker build -t << parameters.image-name >>:$(echo "$CIRCLE_SHA1" | cut -c -7)<< parameters.image-tag-suffix >>  << parameters.docker-file-path >>
      - run:
          name: Tagging << parameters.image-name >> Docker image
          command: docker tag << parameters.image-name >>:$(echo "$CIRCLE_SHA1" | cut -c -7)<< parameters.image-tag-suffix >> << parameters.image-name >>:latest<< parameters.image-tag-suffix >>
      - run:
          name: Archive API Docker image
          command: docker save -o << parameters.image-file >> << parameters.image-name >>
      - persist_to_workspace:
          root: .
          paths:
            - ./<< parameters.image-file >>

  publish:
    parameters:
      image-name:
        type: string
      image-tag-suffix:
        type: string
        default: ''
      image-file:
        type: string
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived << parameters.image-file >> Docker image
          command: docker load -i /tmp/workspace/<< parameters.image-file >>
      - run:
          name: Publish Docker Images to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push << parameters.image-name >>

  deploy-staging:
    docker:
      - image: airhelp/kops:1.10
    steps:
      - checkout
      - run:
          command: |
            # connect to cluster
            export KUBE_CLUSTER=fsi.staging.frontiersi.io
            export KUBE_SERVER=https://api.fsi.staging.frontiersi.io/
            kubectl config set-cluster $KUBE_CLUSTER --server=$KUBE_SERVER --insecure-skip-tls-verify=true
            kubectl config set-credentials $KUBE_USER --token=$KUBE_TOKEN
            kubectl config set-context fsi.staging.frontiersi.io --cluster=$KUBE_CLUSTER --user=$KUBE_USER
            kubectl config use-context fsi.staging.frontiersi.io
            # update image to latest
            export IMAGE_TAG=$(echo "$CIRCLE_SHA1" | cut -c -7)-beta
            kubectl set image --namespace=qa4mbes deployment/api api=ausseabed/spt-api:$IMAGE_TAG
            kubectl set image --namespace=qa4mbes deployment/www www=ausseabed/spt-www:$IMAGE_TAG
            kubectl set image --namespace=qa4mbes deployment/mapserver mapserver=ausseabed/spt-mapserver:$IMAGE_TAG

  build-push-staging-to-ecr:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: STAGING_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: STAGING_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./server
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: STAGING_AWS_ECR_REGISTRY_ID
          repo: ausseabed-staging-sct-api
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
      - aws-ecr/build-and-push-image:
          aws-access-key-id: STAGING_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: STAGING_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./client
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: STAGING_AWS_ECR_REGISTRY_ID
          repo: ausseabed-staging-sct-www
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
      - aws-ecr/build-and-push-image:
          aws-access-key-id: STAGING_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: STAGING_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./map
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: STAGING_AWS_ECR_REGISTRY_ID
          repo: ausseabed-staging-sct-mapserver
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'


workflows:
  build_and_push_staging:
    jobs:
      - build-push-staging-to-ecr:
          <<: *develop_only


  build_and_push_prod:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: PROD_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: PROD_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./server
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: PROD_AWS_ECR_REGISTRY_ID
          repo: ausseabed-prod-sct-api
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
          <<: *master_only
      - aws-ecr/build-and-push-image:
          aws-access-key-id: PROD_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: PROD_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./client
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: PROD_AWS_ECR_REGISTRY_ID
          repo: ausseabed-prod-sct-www
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
          <<: *master_only
      - aws-ecr/build-and-push-image:
          aws-access-key-id: PROD_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: PROD_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./map
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: PROD_AWS_ECR_REGISTRY_ID
          repo: ausseabed-prod-sct-mapserver
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
          <<: *master_only
