develop_only: &develop_only
  filters:
    branches:
      only: develop

master_only: &master_only
  filters:
    branches:
      only: master


version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-eks: circleci/aws-eks@2.2.0

jobs:
  build-push-staging-to-ecr-api:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: STAGING_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: STAGING_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./server
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: STAGING_AWS_ECR_REGISTRY_ID
          repo: ausseabed-staging-sct-api
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
  build-push-staging-to-ecr-www:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: STAGING_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: STAGING_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./client
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: STAGING_AWS_ECR_REGISTRY_ID
          repo: ausseabed-staging-sct-www
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
  build-push-staging-to-ecr-mapserver:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: STAGING_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: STAGING_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./map
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: STAGING_AWS_ECR_REGISTRY_ID
          repo: ausseabed-staging-sct-mapserver
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'


workflows:
  build_push_deploy_staging:
    jobs:
      - build-push-staging-to-ecr-api:
          <<: *develop_only
      - build-push-staging-to-ecr-www:
          <<: *develop_only
      - build-push-staging-to-ecr-mapserver:
          <<: *develop_only
      - aws-eks/update-container-image:
          requires:
              - build-push-staging-to-ecr-api
          aws-region: ap-southeast-2
          cluster-name: ausseabed-nonprod
          resource-name: deployment/api
          container-image-updates: api=288871573946.dkr.ecr.ap-southeast-2.amazonaws.com/ausseabed-staging-sct-api:$CIRCLE_SHA1
          namespace: qa4mbes
          show-kubectl-command: true
      - aws-eks/update-container-image:
          requires:
              - build-push-staging-to-ecr-www
          aws-region: ap-southeast-2
          cluster-name: ausseabed-nonprod
          resource-name: deployment/www
          container-image-updates: www=288871573946.dkr.ecr.ap-southeast-2.amazonaws.com/ausseabed-staging-sct-www:$CIRCLE_SHA1
          namespace: qa4mbes
          show-kubectl-command: true
      - aws-eks/update-container-image:
          requires:
              - build-push-staging-to-ecr-mapserver
          aws-region: ap-southeast-2
          cluster-name: ausseabed-nonprod
          resource-name: deployment/mapserver
          container-image-updates: mapserver=288871573946.dkr.ecr.ap-southeast-2.amazonaws.com/ausseabed-staging-sct-mapserver:$CIRCLE_SHA1
          namespace: qa4mbes
          show-kubectl-command: true

  build_push_prod:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: PROD_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: PROD_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./server
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: PROD_AWS_ECR_REGISTRY_ID
          repo: ausseabed-prod-sct-api
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
          <<: *master_only
      - aws-ecr/build-and-push-image:
          aws-access-key-id: PROD_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: PROD_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./client
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: PROD_AWS_ECR_REGISTRY_ID
          repo: ausseabed-prod-sct-www
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
          <<: *master_only
      - aws-ecr/build-and-push-image:
          aws-access-key-id: PROD_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: PROD_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          executor: aws-ecr/default
          extra-build-args: '--compress'
          no-output-timeout: 20m
          path: ./map
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: ap-southeast-2
          registry-id: PROD_AWS_ECR_REGISTRY_ID
          repo: ausseabed-prod-sct-mapserver
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest,$CIRCLE_SHA1'
          <<: *master_only
