name: Build on push

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: API Build and push develop to staging ECR
    uses: ./.github/workflows/build-push-to-ecr.yml
    with:
      path: server
      image-name: ausseabed-staging-sct-api
      aws-region: ap-southeast-2
      aws-account-id: 288871573946
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_SECRET_ACCESS_KEY }}
